# Generated by Django 5.2.4 on 2025-08-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='claim',
        ),
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attachment'),
        ),
    ]
