# Generated by Django 5.2.4 on 2025-08-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attachment_claim_claim_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='attachment',
        ),
        migrations.AddField(
            model_name='attachment',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.claim'),
        ),
    ]
